### ISSUE TITLE
UT で ActorSystem が 2 重起動してしまっている可能性がある

### ISSUE THREAD

**Issue by negokaz** [lerna-stack/lerna-sample-account-app#20]
Akka Cluster のポート番号が衝突しテストが失敗したため、Application レイヤーの UT で Akka Cluster のポートをランダムに割り当てる対応が必要になった。

5cf88bfa8bb920f7d37ab838ad61c2ae01e0221a

もし ActorSystem が 2 重起動してしまっているとすると、望ましくない状態のため対処したほうが良い。

## きっかけとなった PR

- https://github.com/lerna-stack/lerna-sample-account-app/pull/19

**Comment by tksugimoto** [comment]
Akka の testkit で ActorSystem を afterAll で終了しますが、JDBCSupport の afterAll で `super.afterAll()` が呼ばれていないのでskipされているのが問題だと思います。

`abstract class ScalaTestWithActorTestKit(testKit: ActorTestKit)`
```scala
  override protected def afterAll(): Unit = {
    super.afterAll()
    testKit.shutdownTestKit()
  }
```
``trait JDBCSupport``
```scala
  override def afterAll(): Unit = {
    import tables.profile.api._
    whenReady(jdbcService.db.run(tables.schema.dropIfExists), defaultJDBCTimeout) { _ =>
      // do nothing
    }
  }
```

**Comment by negokaz** [comment]
bddab863469f180d4e8331af5ce70d264242e4f3 にて対処済みです。
